version: '3.8'
services:
  build:
     build: ./venv
     container_name: "build"
     volumes:
       - my_vol:/tmp/boxfuse-sample-java-war-hello/target
  prod:
    image: "tomcat:alpine"
    ports:
      - "8080:8080"
    volumes:
      - my_vol:/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war
    depends_on:
      - build
volumes:
  my_vol:
